sudo: false

#we are not ready to deploy anything
#deploy:
#  provider: pypi
#  user: arokem
#  password:
#    secure: U8Bfe8mXUSp5HYzGsyJfLuVzu+uEt6hid6AQb+HafJMHhhmoiX4cL8IH1xYaT/ZDXR02IO5bpQpjLLvKizDCXrfEgM/YTWhi1lldVh8O6cdP0gBeNfYNQz0qmbWhJFGzN+ad4VXBXrCVIPtF88mmowzRr6P0vLHW8GudSPInJKl6ofUwJDkOOFL6tqAiSLTIlwQQtvKTMqxCAQ3U+kliznpbbjFJSCjf29IQ/tUqzflbKmVdpr5nXCwVONNnydnY8fFK9Vrhl2UchFKjE5KbfoYxFs9udhlgxZMoKSDmTcvhhjwZ7HN8WPABxvY+IvrDi+CUjFDKBKZhSan0fQBfc8aMN0YVE2/TtEJXwsA9g4c3/BkcoF532mc7e2dzExQwOh/xS/iLPhn0qtf+VQn7po7iXwSMbpPIqEOYbgpaWXzgo0Pf5O5Q0pKzuXpcN4femZ1hEtTZ9f13LHuyjLPN9GAZjQmdUGbIkPFY/bbu6ssbkcgKZTABODln68LOnLDQGqpog5bYQ9Myr5mLhF3duLjnoZIcuReyQ7Ed8Z7bcNeiu7t4PAWbgm2DJ3VrUkzq24iUvGedwh3Eqr4eQnedrk2Bn3+rqVv00FjX9elmR7S3TJ4l4jPkfg8R48tDan6wGqhu3s2S97MSmgi+/gWDAEpTBHaHc5DuZ4TcJXTb3To=
#  on:
#    tags: true
#    repo: INCF/pybids

env:
  global:
    - CONDA_DEPS="pip flake8 pytest numpy scipy patsy"

matrix:
  include:
    - os: osx
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh"
    - os: osx
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"


before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda install python=$PYTHON_VERSION $CONDA_DEPS

install:
- pip install -e .

script:
# - flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`
- py.test --pyargs bids

after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache

cache:
  directories:
    - $HOME/miniconda

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
    condition: $PYTHON_VERSION = "3.5"